### PR TITLE
Updates to tests based on class tonight

### PR DESCRIPTION
**Pull request by gotrhythm88**
Hi Celeen,

Here are a few updates to the tests based on our conversations throughout the evening. I've commented my changes in the code. They affect tests 3, 4, 5, 9 and 10.

Please let me know if you have any comments or questions.
Thanks!
Tamasin

### CODE REVIEW

**Comment by celeen** [comment]
Tamasin,

Thank you so much! I'm so excited about this PR. A couple requests, if you don't mind:

1) Thanks for the comments, they're helpful in understanding what you're going for, but I'd love to merge this _without_ the comments. 

2) As far as insert goes, I want this version of the method to reflect python's implementation. Let's name the first one "insert_at_zero" and the second "insert_after_zero"

thanks again for submitting these changes; I'm excited to start implementing the code-pairs to these new tests.

**Comment by gotrhythm88** [comment]
Hi Celeen,
Thanks for the note. Your requests make sense, except that I think the second insert function could be used to insert at zero also. Perhaps it could be named just "insert"? Or "insert_general"?
Let me know!

**Comment by celeen** [comment]
@gotrhythm88 , that's a great call. Let's just call it insert!

Thanks again. :tada: :balloon:

**Comment by gotrhythm88** [comment]
Made the updates. Should be good to go!

**Comment by celeen** [comment]
YIPEE! Thanks!!!

**Pull request merged**
